import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import Timeline from "../components/Timeline";

const Home: NextPage = () => {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <button className='bg-blue-500 px-3 py-2 rounded text-white m-3' onClick={() => signIn()}>Login</button>

        <Timeline/>
      </div>
    </>
  );
};

export default Home;
